#number of max players
#default: 16
max-players: 16

#position of spawn-point in [x,y,z]
#defualt: [0.0,0.0,0.0]
spawn-point: [0.0,0.0,0.0]

#chest loot items
lootItems:
  0:
    material: IRON_SWORD
    enchantments:
      FIRE_ASPECT: 1
    chance: 0.1
    minAmount: 1
    maxAmount: 1
  1:
    material: STEAK
    enchantments:
      LUCK: 1
    chance: 0.5
    minAmount: 1
    maxAmount: 3